from __future__ import annotations
import time
from typing import Dict, Any, List
from UI.nodes.logger import log_state, preview_json, preview_text

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
body {{
  font-family: "WenQuanYi Zen Hei", "DejaVu Sans", "Liberation Sans", sans-serif;
  background-color: #f5f5f5;
  padding: 20px;
  margin: 0;
  width: auto;
}}
.container {{
  background-color: white;
  border-radius: 12px;
  box-shadow: 0 4px 12px rgba(0,0,0,0.1);
  overflow: hidden;
  padding: 20px;
}}
.header {{
  margin-bottom: 16px;
  border-bottom: 1px solid #eee;
  padding-bottom: 10px;
}}
.title {{
  font-size: 18px;
  font-weight: bold;
  color: #333;
}}
.summary {{
  font-size: 14px;
  color: #666;
  margin-top: 4px;
}}
.section {{
  margin-bottom: 20px;
}}
.section-title {{
  font-size: 16px;
  font-weight: 600;
  color: #444;
  margin-bottom: 8px;
}}
.text-content {{
  font-size: 14px;
  line-height: 1.6;
  color: #333;
  white-space: pre-wrap;
}}
.highlight-box {{
  background-color: #e3f2fd;
  border-left: 4px solid #2196f3;
  padding: 12px;
  border-radius: 4px;
  font-size: 14px;
  color: #0d47a1;
}}
.key-value-list {{
  border: 1px solid #eee;
  border-radius: 8px;
}}
.key-value-item {{
  display: flex;
  justify-content: space-between;
  padding: 10px;
  border-bottom: 1px solid #eee;
  font-size: 14px;
}}
.key-value-item:last-child {{
  border-bottom: none;
}}
.key {{
  color: #666;
}}
.value {{
  font-weight: 500;
  color: #333;
}}
.chart-placeholder {{
  background-color: #f0f0f0;
  height: 200px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #888;
  border-radius: 8px;
  font-size: 14px;
}}
.tag-list {{
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}}
.tag {{
  background: #f1f5f9;
  color: #334155;
  border: 1px solid #e2e8f0;
  padding: 6px 10px;
  border-radius: 9999px;
  font-size: 12px;
  line-height: 1;
}}
.button-group {{
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
}}
.button {{
  border: 1px solid #cbd5e1;
  background: #ffffff;
  color: #0f172a;
  padding: 10px 12px;
  border-radius: 10px;
  font-size: 14px;
}}
.button.primary {{
  background: #2563eb;
  border-color: #2563eb;
  color: #ffffff;
}}
.button.secondary {{
  background: #e2e8f0;
  border-color: #e2e8f0;
  color: #0f172a;
}}
.button.outline {{
  background: #ffffff;
}}
.progress-row {{
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  gap: 12px;
  margin-bottom: 8px;
}}
.progress-label {{
  font-size: 14px;
  color: #0f172a;
  font-weight: 500;
}}
.progress-value {{
  font-size: 12px;
  color: #64748b;
}}
.progress {{
  background: #e2e8f0;
  border-radius: 9999px;
  height: 10px;
  overflow: hidden;
}}
.progress > div {{
  background: #2563eb;
  height: 100%;
  width: 0%;
}}
.form-textarea {{
  border: 1px solid #e5e7eb;
  border-radius: 10px;
  padding: 10px;
  font-size: 14px;
  color: #334155;
  min-height: 90px;
  background: #ffffff;
  white-space: pre-wrap;
}}
.form-hint {{
  font-size: 12px;
  color: #64748b;
  margin-top: 6px;
}}
table {{
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}}
th, td {{
  text-align: left;
  padding: 8px;
  border-bottom: 1px solid #ddd;
}}
th {{
  background-color: #f9f9f9;
  font-weight: 600;
}}
.tabs {{
  display: flex;
  gap: 8px;
  margin-bottom: 10px;
  flex-wrap: wrap;
}}
.tab {{
  padding: 8px 10px;
  border: 1px solid #e2e8f0;
  border-radius: 10px;
  background: #f8fafc;
  font-size: 13px;
}}
.card {{
  background: #ffffff;
  border: 1px solid #e5e7eb;
  border-radius: 10px;
  padding: 12px;
}}
.grid {{
  display: grid;
  gap: 10px;
}}
.divider {{
  height: 1px;
  background: #e5e7eb;
  margin: 10px 0;
}}
</style>
</head>
<body>
<div class="container">
<div class="header">
<div class="title">Wabi Assistant</div>
<div class="summary">{summary}</div>
</div>
{content_html}
<div style="text-align: center; margin-top: 20px; font-size: 12px; color: #999;">
Generated by Wabi AI
</div>
</div>
</body>
</html>
"""

def _get(section: Dict[str, Any], key: str, default=None):
    if key in section:
        return section.get(key, default)
    props = section.get("props") or {}
    return props.get(key, default)

def _render_section(section: Dict[str, Any]) -> str:
    t = section.get("type", "text")
    title = _get(section, "title")
    html = '<div class="section">'
    if title:
        html += f'<div class="section-title">{title}</div>'
    if t == "image_display":
        url = _get(section, "image_url") or _get(section, "url")
        caption = _get(section, "caption", "")
        rounded = bool(_get(section, "rounded", True))
        width = _get(section, "width")
        height = _get(section, "height")
        if url:
            style_parts = ["max-width:100%", "height:auto", "display:block", "margin:0 auto 8px", "object-fit:contain"]
            if rounded:
                style_parts.append("border-radius:12px")
            if isinstance(width, (int, float)):
                style_parts.append(f"width:{int(width)}px")
            if isinstance(height, (int, float)):
                style_parts.append(f"max-height:{int(height)}px")
            style = ";".join(style_parts)
            html += f'<img src="{url}" alt="{caption}" style="{style}"/>'
            if caption:
                html += f'<div class="text-content" style="font-size:12px;color:#666;margin-top:4px;">{caption}</div>'
        else:
            html += '<div class="chart-placeholder">图片加载失败</div>'
    elif t == "text":
        content = _get(section, "content", "")
        html += f'<div class="text-content">{content}</div>'
    elif t == "markdown":
        content = _get(section, "content", "")
        html += f'<div class="text-content">{content}</div>'
    elif t == "highlight_box" or t == "alert":
        content = _get(section, "content", "")
        html += f'<div class="highlight-box">{content}</div>'
    elif t == "key_value_list":
        html += '<div class="key-value-list">'
        for item in _get(section, "items", []) or []:
            label = item.get("label", "")
            value = item.get("value", "")
            html += f'<div class="key-value-item"><span class="key">{label}</span><span class="value">{value}</span></div>'
        html += '</div>'
    elif t == "place_table":
        html += '<table><thead><tr><th>Name</th><th>Rating</th><th>Price</th></tr></thead><tbody>'
        for item in _get(section, "items", []) or []:
            name = item.get("name", "")
            rating = item.get("rating", "-")
            price = item.get("price_str", "-")
            html += f'<tr><td>{name}</td><td>{rating}</td><td>{price}</td></tr>'
        html += '</tbody></table>'
    elif t in ["bar_chart", "pie_chart", "line_chart", "radar_chart"]:
        chart_title = _get(section, "title", "")
        items = _get(section, "items")
        labels: List[str] = []
        values: List[float] = []
        if items:
            labels = [str(item.get("label", "")) for item in items]
            values = [float(item.get("value", 0)) for item in items]
        else:
            if t == "line_chart":
                labels = [str(x) for x in _get(section, "labels", []) or []]
                values = [float(x) for x in _get(section, "points", []) or []]
            elif t == "radar_chart":
                labels = [str(x) for x in _get(section, "axes", []) or []]
                values = [float(x) for x in _get(section, "values", []) or []]
        if chart_title:
            html += f'<div class="text-content" style="font-weight:600;margin-bottom:6px;">{chart_title}</div>'
        if t == "bar_chart":
            max_val = max(values) if values else 0.0
            max_val = max_val if max_val > 0 else 1.0
            html += '<div class="key-value-list">'
            for label, value in zip(labels, values):
                percent = int(round(max(0.0, min(1.0, value / max_val)) * 100))
                html += f'<div class="key-value-item"><span class="key">{label}</span><span class="value">{value}</span></div>'
                html += f'<div class="progress"><div style="width:{percent}%;"></div></div>'
            html += '</div>'
        elif t == "pie_chart":
            total = sum(values) if values else 0.0
            total = total if total > 0 else 1.0
            html += '<div class="key-value-list">'
            for label, value in zip(labels, values):
                percent = int(round(max(0.0, min(1.0, value / total)) * 100))
                html += f'<div class="key-value-item"><span class="key">{label}</span><span class="value">{percent}%</span></div>'
            html += '</div>'
        else:
            html += '<table><thead><tr><th>Label</th><th>Value</th></tr></thead><tbody>'
            for label, value in zip(labels, values):
                html += f'<tr><td>{label}</td><td>{value}</td></tr>'
            html += '</tbody></table>'
    elif t == "statistic_grid":
        columns = _get(section, "columns", 2)
        try:
            columns = int(columns)
        except Exception:
            columns = 2
        columns = max(1, min(columns, 4))
        html += f'<div class="grid" style="grid-template-columns: repeat({columns}, 1fr);">'
        for item in _get(section, "items", []) or []:
            label = item.get("label", "")
            value = item.get("value", "")
            html += f'<div class="card"><div style="font-size:12px; color:#666;">{label}</div><div style="font-size:16px; font-weight:bold;">{value}</div></div>'
        html += '</div>'
    elif t == "tag_list":
        tags = _get(section, "tags", []) or []
        html += '<div class="tag-list">'
        for tag in tags:
            html += f'<span class="tag">{tag}</span>'
        html += '</div>'
    elif t == "button_group":
        buttons = _get(section, "buttons", []) or []
        html += '<div class="button-group">'
        for btn in buttons:
            label = btn.get("label", "")
            variant = (btn.get("variant") or "outline").strip().lower()
            if variant not in {"primary", "secondary", "outline"}:
                variant = "outline"
            html += f'<button class="button {variant}" type="button">{label}</button>'
        html += '</div>'
    elif t == "progress_bar":
        label = _get(section, "label", "")
        value = _get(section, "value", 0) or 0
        max_value = _get(section, "max", 100) or 100
        show_percent = bool(_get(section, "show_percent", True))
        try:
            value_f = float(value)
        except Exception:
            value_f = 0.0
        try:
            max_f = float(max_value)
        except Exception:
            max_f = 100.0
        ratio = 0.0 if max_f <= 0 else max(0.0, min(1.0, value_f / max_f))
        percent = int(round(ratio * 100))
        right_text = f"{percent}%" if show_percent else f"{value}/{max_value}"
        html += f'<div class="progress-row"><div class="progress-label">{label}</div><div class="progress-value">{right_text}</div></div>'
        html += f'<div class="progress"><div style="width:{percent}%;"></div></div>'
    elif t == "feedback_form":
        placeholder = _get(section, "placeholder", "")
        submit_label = _get(section, "submit_label", "")
        html += f'<div class="form-textarea">{placeholder}</div>'
        if submit_label:
            html += f'<div class="form-hint">{submit_label}</div>'
    elif t == "tabs":
        tabs = _get(section, "tabs", []) or []
        html += '<div class="tabs">'
        for tab in tabs:
            html += f'<div class="tab">{tab.get("label","")}</div>'
        html += '</div>'
        for tab in tabs:
            content = tab.get("content","")
            html += f'<div class="text-content">{content}</div>'
    elif t == "collapsible_section":
        content = _get(section, "content", "")
        html += f'<div class="card">{content}</div>'
    elif t == "card_list":
        items = _get(section, "items", []) or []
        for item in items:
            title = item.get("title","")
            subtitle = item.get("subtitle","")
            image_url = item.get("image_url")
            badge = item.get("badge","")
            content = item.get("content","")
            html += '<div class="card">'
            if image_url:
                html += f'<img src="{image_url}" style="max-width:100%;border-radius:8px;margin-bottom:8px;" />'
            if title:
                html += f'<div class="section-title">{title}</div>'
            if subtitle:
                html += f'<div class="text-content" style="color:#64748b;">{subtitle}</div>'
            if badge:
                html += f'<div class="tag" style="display:inline-block;margin:6px 0;">{badge}</div>'
            if content:
                html += f'<div class="text-content">{content}</div>'
            html += '</div>'
    elif t == "gallery_grid":
        columns = _get(section, "columns", 3)
        try:
            columns = int(columns)
        except Exception:
            columns = 3
        columns = max(1, min(columns, 6))
        html += f'<div class="grid" style="grid-template-columns: repeat({columns}, 1fr);">'
        for img in _get(section, "images", []) or []:
            src = img.get("src")
            caption = img.get("caption","")
            if src:
                html += '<div class="card">'
                html += f'<img src="{src}" style="max-width:100%;border-radius:8px;" />'
                if caption:
                    html += f'<div class="text-content" style="font-size:12px;color:#666;margin-top:4px;">{caption}</div>'
                html += '</div>'
        html += '</div>'
    elif t == "rating_badge":
        label = _get(section, "label","")
        rating = _get(section, "rating", 0)
        maxv = _get(section, "max", 5)
        html += f'<div class="tag">{label} {rating}/{maxv}</div>'
    elif t == "table_advanced":
        columns = _get(section, "columns", []) or []
        rows = _get(section, "rows", []) or []
        html += '<table><thead><tr>'
        for c in columns:
            html += f'<th>{c}</th>'
        html += '</tr></thead><tbody>'
        for row in rows:
            html += '<tr>'
            for cell in row:
                html += f'<td>{cell}</td>'
            html += '</tr>'
        html += '</tbody></table>'
        footnote = _get(section, "footnote")
        if footnote:
            html += f'<div class="text-content" style="font-size:12px;color:#64748b;margin-top:6px;">{footnote}</div>'
    elif t == "divider":
        html += '<div class="divider"></div>'
    elif t == "spacer":
        h = _get(section, "height", 10)
        try:
            h = int(h)
        except Exception:
            h = 10
        html += f'<div style="height:{h}px;"></div>'
    elif t == "custom_html":
        html_content = _get(section, "html_content", "")
        html += html_content
    else:
        content = str(section.get("content", ""))
        html += f'<div class="text-content">{content}</div>'
    html += '</div>'
    return html

def build_html_from_plan(ui_plan: Dict[str, Any]) -> str:
    summary = ui_plan.get("summary", "")
    content_html = ""
    for section in ui_plan.get("sections", []) or []:
        content_html += _render_section(section)
    full_html = HTML_TEMPLATE.format(summary=summary, content_html=content_html)
    return full_html

def builder(state: Dict[str, Any]) -> Dict[str, Any]:
    t0 = time.perf_counter()
    state["current_node"] = "builder"
    ui_plan = state.get("ui_plan") or {}
    log_state(
        state,
        "info",
        "Builder started",
        node="builder",
        event="node_start",
        data={
            "mode": ui_plan.get("mode") if isinstance(ui_plan, dict) else None,
            "sections": len(ui_plan.get("sections", []) or []) if isinstance(ui_plan, dict) else None,
        },
    )
    log_state(state, "debug", "Builder plan preview", node="builder", event="plan_preview", data={"plan": preview_json(ui_plan, limit=1500)})
    html = build_html_from_plan(ui_plan)
    log_state(
        state,
        "info",
        "Builder HTML built",
        node="builder",
        event="html_built",
        data={"html": preview_text(html), "duration_ms": int((time.perf_counter() - t0) * 1000)},
    )
    return {"html_content": html}
